// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Xna.Framework.GamerServices;

#nullable disable

namespace Microsoft.Xna.Framework.GamerServices.Migrations
{
    [DbContext(typeof(AchievementContext))]
    partial class AchievementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Microsoft.Xna.Framework.GamerServices.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisplayBeforeEarned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EarnedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EarnedOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamerScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HowToEarn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_IconPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });
#pragma warning restore 612, 618
        }
    }
}
