//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPR.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPR.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application already installed.
        /// </summary>
        public static string ApplicationAlreadyInstalled {
            get {
                return ResourceManager.GetString("ApplicationAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application {0} has already been installed. Do you want to delete the existing application and install this package?.
        /// </summary>
        public static string ApplicationAlreadyInstalledDescription {
            get {
                return ResourceManager.GetString("ApplicationAlreadyInstalledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation has been canceled!.
        /// </summary>
        public static string ApplicationInstallError_Canceled {
            get {
                return ResourceManager.GetString("ApplicationInstallError_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application package contains invalid manifest files!.
        /// </summary>
        public static string ApplicationInstallError_InvalidManifestFiles {
            get {
                return ResourceManager.GetString("ApplicationInstallError_InvalidManifestFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application package is missing manifest files!.
        /// </summary>
        public static string ApplicationInstallError_MissingManifestFiles {
            get {
                return ResourceManager.GetString("ApplicationInstallError_MissingManifestFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been successfully installed!.
        /// </summary>
        public static string ApplicationInstallError_None {
            get {
                return ResourceManager.GetString("ApplicationInstallError_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application package is not in decrypted format!.
        /// </summary>
        public static string ApplicationInstallError_NotDecrypted {
            get {
                return ResourceManager.GetString("ApplicationInstallError_NotDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application type is currently not yet supported!.
        /// </summary>
        public static string ApplicationInstallError_NotSupportedAppType {
            get {
                return ResourceManager.GetString("ApplicationInstallError_NotSupportedAppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured during the installation.&amp;#13;&amp;#13;Please check the log for more info..
        /// </summary>
        public static string ApplicationInstallError_UnexpectedError {
            get {
                return ResourceManager.GetString("ApplicationInstallError_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing application.
        /// </summary>
        public static string AppRunError {
            get {
                return ResourceManager.GetString("AppRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowsePath {
            get {
                return ResourceManager.GetString("BrowsePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data storage.
        /// </summary>
        public static string DataStoragePath {
            get {
                return ResourceManager.GetString("DataStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your GamerTag....
        /// </summary>
        public static string EnterYourGamerTag {
            get {
                return ResourceManager.GetString("EnterYourGamerTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application encountered an unexpected error while executing. Please check the log for more detailed info!.
        /// </summary>
        public static string ExceptionRunApp {
            get {
                return ResourceManager.GetString("ExceptionRunApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed.
        /// </summary>
        public static string InstallationFailed {
            get {
                return ResourceManager.GetString("InstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation succeed.
        /// </summary>
        public static string InstallationSucceed {
            get {
                return ResourceManager.GetString("InstallationSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing application....
        /// </summary>
        public static string InstallingApp {
            get {
                return ResourceManager.GetString("InstallingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install new application.
        /// </summary>
        public static string InstallNewAppToolTip {
            get {
                return ResourceManager.GetString("InstallNewAppToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching in process....
        /// </summary>
        public static string LaunchingInProcess {
            get {
                return ResourceManager.GetString("LaunchingInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result default data storage path.
        /// </summary>
        public static string RestoreDefaultStorage {
            get {
                return ResourceManager.GetString("RestoreDefaultStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for applications....
        /// </summary>
        public static string SearchForAppSearchBar {
            get {
                return ResourceManager.GetString("SearchForAppSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed.
        /// </summary>
        public static string SuccessfullyChanged {
            get {
                return ResourceManager.GetString("SuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data directory will be used for the next launch of the runner!.
        /// </summary>
        public static string SuccessfullyChangedDataPathMsg {
            get {
                return ResourceManager.GetString("SuccessfullyChangedDataPathMsg", resourceCulture);
            }
        }
    }
}
